import { build } from 'esbuild';
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { createHash } from 'node:crypto';
import path from 'node:path';

const result = await build({
  entryPoints: {
    main: 'main.js',
    'editor.worker': 'monaco-editor/esm/vs/editor/editor.worker.js',
    'json.worker': 'monaco-editor/esm/vs/language/json/json.worker.js',
    'graphql.worker': 'monaco-graphql/esm/graphql.worker.js',
  },
  outdir: 'dist',
  bundle: true,
  minify: true,
  format: 'esm',
  target: 'es2022',
  define: { 'process.env.NODE_ENV': '"production"' },
  loader: { '.ttf': 'dataurl', '.woff2': 'dataurl', '.woff': 'dataurl' },
  legalComments: 'external',
  metafile: true,
  write: false,
});

// Preserve the license text for every package included in the bundle.
const packages = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const parts = input.split('/');
  const index = parts.lastIndexOf('node_modules');
  if (index >= 0) {
    packages.add(parts.slice(0, index + (parts[index + 1].startsWith('@') ? 3 : 2)).join('/'));
  }
}
const notices = [];
for (const directory of [...packages].sort()) {
  const pkg = JSON.parse(await readFile(`${directory}/package.json`, 'utf8'));
  notices.push(`\n## ${pkg.name} ${pkg.version} (${pkg.license || 'see license'})\n`);
  const files = (await readdir(directory)).filter(name => /^(license|copying|notice)([-.]|$)/i.test(name)).sort();
  if (!files.length && pkg.repository?.url === 'https://github.com/graphql/graphiql' && pkg.license === 'MIT') {
    notices.push(await readFile('node_modules/graphiql/LICENSE', 'utf8'));
  } else if (!files.length && pkg.name === 'react-compiler-runtime' && pkg.license === 'MIT') {
    notices.push(await readFile('node_modules/react/LICENSE', 'utf8'));
  } else if (!files.length && pkg.name === 'react-remove-scroll-bar' && pkg.version === '2.3.8') {
    notices.push(await readFile('licenses/react-remove-scroll-bar.txt', 'utf8'));
  } else {
    if (!files.length) throw new Error(`Missing license: ${directory}`);
    for (const file of files) notices.push(await readFile(`${directory}/${file}`, 'utf8'));
  }
}
await mkdir('dist', { recursive: true });
const noticeText = notices.join('\n').replace(/\r\n/g, '\n').replace(/[\t ]+$/gm, '');
await writeFile('dist/THIRD_PARTY_NOTICES.txt', noticeText);
result.outputFiles.push({ path: 'THIRD_PARTY_NOTICES.txt', contents: Buffer.from(noticeText) });
const assets = [];
const hashes = [];
for (const file of result.outputFiles.sort((a, b) => path.basename(a.path).localeCompare(path.basename(b.path), 'en'))) {
  const name = path.basename(file.path);
  const bytes = gzipSync(file.contents, { level: 9 });
  await writeFile(`dist/${name}.gz`, bytes);
  hashes.push(`${createHash('sha256').update(bytes).digest('hex')}  ${name}.gz`);
  const mime = name.endsWith('.js') ? 'text/javascript' : name.endsWith('.css') ? 'text/css' : 'text/plain';
  assets.push(`    ("${name}", "${mime}", include_bytes!(concat!(env!("CARGO_MANIFEST_DIR"), "/web/dist/${name}.gz"))),`);
}
await writeFile('dist/assets.rs', `// Generated by web/build.mjs.\npub const ASSETS: &[(&str, &str, &[u8])] = &[\n${assets.join('\n')}\n];\n`);
await writeFile('dist/SHA256SUMS', `${hashes.join('\n')}\n`);
